[project]
name = "iot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0,<2.0.0",
    "opencv-python-headless>=4.5.0",
    "picamera2>=0.3.33",
]
